apiVersion: mlops.sathvik.dev/v1
kind: ModelDeployment
metadata:
  name: dummy-model
spec:
  modelURI: https://dummy.com/dummy_model.pt
  runtime: fastapi-pytorch
  runtimeImage: "localhost/fastapi-pytorch:dev" # <-- override used
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"
  validateScript: "validate.py"
  autoscale: false
  version: v1
