# podmonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: dummy-inference-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      model: dummy-model
  podMetricsEndpoints:
    - path: /metrics
      targetPort: 8000
      interval: 15s
