# This rule is not used by the project model-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to mlops.sathvik.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: model-operator
    app.kubernetes.io/managed-by: kustomize
  name: modeldeployment-viewer-role
rules:
- apiGroups:
  - mlops.sathvik.dev
  resources:
  - modeldeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mlops.sathvik.dev
  resources:
  - modeldeployments/status
  verbs:
  - get
