---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - mlops.sathvik.dev
  resources:
  - modeldeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mlops.sathvik.dev
  resources:
  - modeldeployments/finalizers
  verbs:
  - update
- apiGroups:
  - mlops.sathvik.dev
  resources:
  - modeldeployments/status
  verbs:
  - get
  - patch
  - update
