apiVersion: mlops.sathvik.dev/v1
kind: ModelDeployment
metadata:
  labels:
    app.kubernetes.io/name: model-operator
    app.kubernetes.io/managed-by: kustomize
  name: modeldeployment-sample
spec:
  # TODO(user): Add fields here
